---
name: ardo_app-aws
director_uuid: d63a8a9c-4c3b-4dc3-a164-87d3c798c815

releases:
- {name: ardo_app, version: latest}


networks:
- name: my-net
  type: dynamic
  subnets:
  - range: 192.168.1.0/24
    dns: [192.168.0.1]
    gateway: 192.168.1.1
    cloud_properties:
      subnet: subnet-6eb40118
      security_groups: [sg-74b51512]
      availability_zone: us-west-2b
- name: public
  type: vip


jobs:
- name: web_ui
  instances: 1
  templates:
  - {name: web_ui, release: ardo_app}
  resource_pool: pool1
  networks:
  - name: my-net
#    static_ips: [192.168.1.152]
    default: [dns, gateway]
#  persistent_disk: 10_240
  - name: public
    static_ips: [52.33.121.136] 

- name: bg_worker
  instances: 1
  templates:
  - {name: bg_worker, release: ardo_app}
  resource_pool: pool1
  networks:
  - name: my-net
#    static_ips: [192.168.1.153]
#    default: [dns, gateway]
#  persistent_disk: 10_240


    
update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

compilation:
  workers: 2
  network: my-net
  reuse_compilation_vms: true
  cloud_properties:
    availability_zone: us-west-2b
    instance_type: t2.medium


resource_pools:
- name: pool1
  network: my-net
  stemcell:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3262.2
  cloud_properties:
    instance_type: t2.small
    availability_zone: us-west-2b
    ephemeral_disk: {size: 25_000, type: gp2}

properties:
  web_ui:
    port: 80
